"""Add guardian_email to students table

Revision ID: 510d2c8b0f6c
Revises: 737205b0dded
Create Date: 2026-02-13 23:12:52.409236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510d2c8b0f6c'
down_revision = '737205b0dded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('guardian_email')
    # ### end Alembic commands ###