"""Add signature_path and photo_path to students table

Revision ID: 737205b0dded
Revises: 
Create Date: 2026-02-09 22:14:51.582049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737205b0dded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('signature_path')

    # ### end Alembic commands ###
